FROM --platform=linux/x86_64 golang:1.21-alpine

WORKDIR /app
COPY ./go.mod ./go.sum ./Makefile ./
RUN apk update && \
    apk add --update --no-cache git && \
    apk add --no-cache gcc && \
    apk add --no-cache musl-dev && \
    apk add --no-cache make && \
    wget https://github.com/golang-migrate/migrate/releases/download/v4.15.0/migrate.linux-amd64.tar.gz && \
    tar -zxvf migrate.linux-amd64.tar.gz && \
    mkdir -p /usr/local/bin && \
    mv migrate /usr/local/bin/migrate

RUN go mod download
RUN make tools

# ソースコードのコピー docker-cmposeでは、volume(バインドマウントではない方)の一部だけのマウントはできない。
COPY ./main.go ./
COPY  api/ ./api
COPY adapter/ ./adapter
COPY config/ ./config
COPY domain/ ./domain
COPY features/ ./features
COPY interactor/ ./interactor/
COPY interface/ ./interface
COPY log/ ./log
COPY util/ ./util

EXPOSE 80
