# 開発用の構成
services:
  api:
    build:
      context: .
      dockerfile: ./dev_dockerfiles/dockerfile.api
    ports:
      - 80:80
    tty: true
    env_file: .env
    command: >
      ash -c "go run main.go"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: .
      dockerfile: ./dev_dockerfiles/dockerfile.mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_NAME}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD==${DB_PASSWORD}
    ports:
      - 4040:80
    depends_on:
      mysql:
        condition: service_healthy
